### ISSUE TITLE
"Trigger Notification" contract

### ISSUE THREAD

**Issue by TylerLeonhardt** [Windos/PoshNotify#2]
Let's use this to discuss the exact cmdlet name and parameters for this abstraction layer 👍

**Comment by Windos** [comment]
My suggestion for cmdlet name is: "Send-PoshNotification", possibly with an alias of "notify".

Parameters:

- Title
- Body
- Icon

I'm not sure if we can abstract sounds? Unless they're kept generic, like "IM" "Reminder" "Alarm" etc. and they can be mapped to respective sounds on each OS?

**Comment by TylerLeonhardt** [comment]
That looks like a good start.

I think we could also include Duration (as in how long the notification shows)? But that's not really a high priority and most Linux distros don't even implement it and silently use whatever default duration is available.

Sound would be a good one. That'd be Windows & macOS only which begs me to ask:

How should we handle a platform not supporting a feature? How would linux respond if a sound is passed in?

I was thinking it writes an error "Platform not supported" and we could add a param like `-Force` or `-Quiet` that will still send the notification but obviously no special sound.

**Comment by Windos** [comment]
I'm leaning towards a warning and dropping the unsupported feature when calling the private function.

I can't help but think of someone writing a script that's meant to run on multiple systems with this in it... but doesn't realise "x" isn't supported until someone else runs it on Linux vs macOS (for e.g.)

The other scenario to consider is authoring something on local (say Windows) workstation and invoking it on a remote Linux system.

**Comment by TylerLeonhardt** [comment]
Good idea. We should be as resilient as possible.

In PSNotifySend, the only parameter I had mandatory was `Body` because `Title` defaulted to "PowerShell Notification" and the icon defaulted to the PowerShell logo.

Do we want to follow that?

That way, all you gotta do is call:

```powershell
Send-PoshNotification Hello
```

**Comment by steviecoaster** [comment]
I'm a fan of Pop for the verb, that more aligns with the action. 

As for Sound, I know Windows and Mac have a default set that could be used. Linux may be a bit trickier, unless we include a secondary executable call to a utility that parses a sound file.

**Comment by steviecoaster** [comment]
I should clarify I like Pop for the Private functions. Send makes sense in the public sense, since it will potentially be invoked on a remote workstation.

**Comment by steviecoaster** [comment]
I think Title should not be Mandatory. We can initialize in the declaration.  If people want to override they can, bit making it as streamlined as we can is super agreeable to me.

**Comment by Windos** [comment]
Strictly speaking, even body doesn't need to be mandatory. The result isn't exactly **useful**, but it'd be valid. e.g. with BurntToast you can run `toast` and get:

![example1-default](https://user-images.githubusercontent.com/6955786/48925402-0b2c8f00-ef28-11e8-8a05-357069886ddb.png)

(n.b. not saying that's a good thing, btw!)

Personally, for this I vote keep `title` as optional (we can have a default) and `body` as mandatory, forces user to make the toast useful

**Comment by TylerLeonhardt** [comment]
We could, later, make body NOT mandatory and then fill it with random funny sayings, maybe 😊

**Comment by steviecoaster** [comment]
There's probably an API for that LOL

**Comment by markwragg** [comment]
Do cmdlet names need to include the word Posh? I always feel like it’s a bit redundant.

**Comment by Stephanevg** [comment]
I agree with @markwragg as having 'Posh' in the name of cmdlet brings nothing additional to  game when you just look at the cmdlet name.

I  personally try to add the prefix of the module name in every cmdlet I write, so that in that manner, when you do a plain 'Get-Command' you can immediatley recognize from which module which cmdlet actually comes.

Generaly, I try to limit myself to 2 or 3 letters following the cmdlet verb.

For BurntToast module for example, I could see the prefix be: 'BT' and then, the cmdlet could be `Send-BTNotification`

Since this module is called 'PoshNotify' I think something along the lines of: `Send-PSNNotification` or 'Send-NONotification'.

Note: while writing this comment, I was thinking about the name of this module, and what it actually does. I see this is a 'univerals notifier' solution. Where the prefixes could be 'UN' or 'UNT'. So, something like: `Send-UNNotification` or `Send-UNTNotification`
Just saying... ;)

**Comment by Stephanevg** [comment]
The suggestion of @markwragg on the hand for `Send-OSNotification` is a good case for **only** that cmdlet. This would imply, if we want to follow module design best practises, that all cmdlets that would be added in this module have the same prefix as this one, which means, 'OS', which IMO, is not 100% accurate, because these cmdlets are supposed to be for notification, not specifically only for OS stuff.
Perhaps, `Send-PSNOSNotification`  / or 'Send-UNTOsNotification' are better options?

**Comment by Windos** [comment]
I personally wouldn't get too hung up on the naming of the private functions. People are only going to see them if they dive into the code/do a PR, etc.

For the function in question, how about we drop the prefix in general: `Send-Notification`?

Or does that become **too** generic?

**Comment by TylerLeonhardt** [comment]
Seems a bit too generic. I like `Send-OSNotification` for now :) we can always change it later. 

Also, I think we should also support ShouldProcess where it informs the exact command that is getting run on the platform you're on.

So:

```powershell
Send-OSNotification "Hello World!" -WhatIf
```

Says you're running:

```powershell
Invoke-MacNotification -Body "Hello World!" 
```

**Comment by TylerLeonhardt** [comment]
I think we can close this now that we have a good start. For changes and added params we can open new issues :)
